Repository Azure/AzOps, pull requests merged in 2020-08, with the labels that each got.

#126 Relax pull requirements before push to optimise performance in large environment
  src/public/Invoke-AzOpsGitPush.ps1
Labels: enhancement :rocket:

#125 Add Azure DevOps support
  Dockerfile
  entrypoint.ps1
  src/auxiliary/guidance/strict/azdevops/README.md
  src/auxiliary/guidance/strict/github/README.md
  src/auxiliary/providerfeatures.json
  src/auxiliary/resourceproviders.json
  src/private/ConvertTo-AzOpsState.ps1
  src/private/Get-AzOpsAllSubscription.ps1
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
  src/private/New-AzOpsStateDeployment.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  src/public/Initialize-AzOpsRepository.ps1
  src/public/Invoke-AzOpsGitPull.ps1
  src/public/Invoke-AzOpsGitPush.ps1
  tests/AzOps.IAB.Tests.ps1
Labels: feature :bulb:

#129 Adding switch to ignore exit code for gh pr merge
  src/public/Invoke-AzOpsGitPull.ps1
Labels: bug :ambulance:

#130 Fix Azure Pipelines badge
  README.md
Labels: bug :ambulance:

#138 bug fix for case sensitive effectiveResourceType
  src/private/Invoke-AzOpsChange.ps1
Labels: bug :ambulance:

#140 Adding Prefix to Az Deployment Name
  src/private/Invoke-AzOpsChange.ps1
  tests/AzOps.IAB.Tests.ps1
Labels: feature :bulb:

#142 Fix uninitialized variable
  src/public/Invoke-AzOpsGitPush.ps1
Labels: bug :ambulance:

#144 Renaming MG, Sub and RG filename to be consistent with other resources
  src/AzOps.psm1
  src/private/New-AzOpsDeployment.ps1
  src/public/Initialize-AzOpsRepository.ps1
  tests/AzOps.Scope.Tests.ps1
Labels: do not merge :construction:

#150 Roleassignment bugfix
  src/private/ConvertTo-AzOpsObject.ps1
Labels: bug :ambulance:

#151 Bugfix - RoleDefinition ordering
  src/private/ConvertTo-AzOpsState.ps1
  src/private/Get-AzOpsRoleDefinitionAtScope.ps1
Labels: bug :ambulance:

#152 Adding support for managed identity for policy effect type modify
  template/tenant.json
Labels: bug :ambulance:

#154 Get-AzManagementGroup changes and new target module versions
  .azure-pipelines/ubuntu-latest.yml
  src/AzOps.psd1
  src/private/Get-AzOpsAllManagementGroup.ps1
  src/private/Remove-AzOpsManagementGroup.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  tests/AzOps.IAB.Tests.ps1
Labels: enhancement :rocket:
