Repository Azure/AzOps, pull requests merged in 2020-07, with the labels that each got.

#63 BugFix - Enabling Subscription Move
  template/tenant.json
  tests/AzOps.Module.Tests.ps1
Labels: feature

#64 Adding Schema for AzOps ARM Template
  .vscode/settings.json
  schema/2020-08-01/azstate.json
Labels: feature

#66 Fix Schema Id
  schema/2020-08-01/azstate.json
Labels: bug

#69 Feature - Action to use docker image
  .github/workflows/release.yml
  action.yml
Labels: feature

#71 Add Super-Linter to GitHub Actions
  .azure-pipelines/ubuntu-latest.yml
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/code-review-pull.yml
  .github/workflows/code-review-push.yml
  README.md
  entrypoint.ps1
  src/AzOps.psd1
  src/AzOps.psm1
  src/Comments.md
  src/private/Compare-AzOpsState.ps1
  src/private/ConvertTo-AzOpsObject.ps1
  src/private/ConvertTo-AzOpsState.ps1
  src/private/ConvertTo-AzOpsTemplateParameterObject.ps1
  src/private/Get-AzOpsPolicyAssignmentAtScope.ps1
  src/private/Get-AzOpsPolicyDefinitionAtScope.ps1
  src/private/Get-AzOpsPolicySetDefinitionAtScope.ps1
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
  src/private/Get-AzOpsRoleAssignmentAtScope.ps1
  src/private/Get-AzOpsRoleDefinitionAtScope.ps1
  src/private/Invoke-AzOpsGitPullRefresh.ps1
  src/private/Invoke-AzOpsGitPushRefresh.ps1
  src/private/New-AzOpsStateDeployment.ps1
  src/private/Register-AzOpsProviderFeature.ps1
  src/private/Register-AzOpsResourceProvider.ps1
  src/private/Remove-AzOpsDeployments.ps1
  src/private/Remove-AzOpsManagementGroup.ps1
  src/private/Save-AzOpsManagementGroupChildren.ps1
  src/private/Start-AzOpsNativeExecution.ps1
  src/private/Test-AzOpsDuplicateSubMgmtGroup.ps1
  src/private/Test-AzOpsVariables.ps1
  src/private/Write-AzOpsLog.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  src/public/Initialize-AzOpsRepository.ps1
  src/public/Invoke-AzOpsGitPull.ps1
  src/public/Invoke-AzOpsGitPush.ps1
  src/resourceproviders.json
  template/20-create-child-managementgroup.parameters.json
  template/30-create-policydefinition-at-managementgroup.parameters.json
  template/enterprise-scale-arm-template.json
  template/esux.json
  template/template.json
  template/tenant.json
  template/ux-foundation.json
  template/ux-vwan.json
  tests/AzOps.Cmdlets.Tests.ps1.ignore
  tests/AzOps.IAB.Tests.ps1
  tests/AzOps.Module.Tests.ps1
  tests/AzOps.PSScriptAnalyzer.Tests.ps1.ignore
  tests/scripts/Initialize-AzOpsTestEnvironment.ps1
Labels: feature

#72 Fix Deployment Name for PolicySetDefinitions
  template/tenant.json
Labels: bug

#65 [Feature] Discovery enhancements
  entrypoint.ps1
  src/AzOps.psm1
  src/private/Get-AzOpsAllManagementGroup.ps1
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
  src/private/New-AzOpsStateDeployment.ps1
  src/private/Save-AzOpsManagementGroupChildren.ps1
  src/private/Test-AzOpsDuplicateSubMgmtGroup.ps1
  src/private/Test-AzOpsRuntime.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  src/public/Initialize-AzOpsRepository.ps1
  tests/AzOps.IAB.Tests.ps1
  tests/AzOps.Module.Tests.ps1
  tests/AzOps.Scope.Tests.ps1
Labels: feature

#73 Removing Version Label from container
  Dockerfile
Labels: enhancement

#74 Feature Adding workflow_dispatch for release action
  .github/workflows/release.yml
  action.yml
Labels: enhancement

#75 Feature-Create Branch Workflow to change branch reference
  .github/workflows/branch.yml
  src/AzOps.psd1
  tests/AzOps.Module.Tests.ps1
Labels: enhancement

#78 Refactor release workflow
  .github/workflows/branch.yml
  .github/workflows/release.yml
Labels: bug :ambulance:

#80 Remove module whitespace
  .github/workflows/branch.yml
Labels: bug :ambulance:

#81 Rename image label
  .github/workflows/branch.yml
Labels: bug :ambulance:

#79 Set version for github/super-linter:v3.3.0
  .github/workflows/code-review-pull.yml
  .github/workflows/code-review-push.yml
Labels: enhancement :rocket:

#83 Update error message
  src/private/Test-AzOpsRuntime.ps1
Labels: bug :ambulance:

#85 Update badge status
  README.md
Labels: bug :ambulance:

#87 Updated fix to handle stale subscriptions
  entrypoint.ps1
  src/AzOps.psm1
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
  src/private/Save-AzOpsManagementGroupChildren.ps1
Labels: bug :ambulance:

#86 Fix ShouldProcess Issue
  src/private/Start-AzOpsNativeExecution.ps1
Labels: bug :ambulance:

#88 updated logic and added check for git longpath setting
  src/private/Test-AzOpsRuntime.ps1
Labels: enhancement :rocket:

#91 Fix issue labels
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Labels: bug :ambulance:

#92 Fix issue labels
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Labels: bug :ambulance:

#95 fixing broken link
  README.md
Labels: documentation :page_facing_up:

#19 Support Azure DevOps
  src/Comments-ado.md
  src/public/Invoke-AzOpsGitPull.ps1
  src/public/Invoke-AzOpsGitPush.ps1
Labels: feature :bulb:

#96 Removed duplicate timestamps
  src/public/Initialize-AzOpsGlobalVariables.ps1
Labels: enhancement :rocket:

#97 Fix global variables - generalize templates and export raw templates
  src/private/ConvertTo-AzOpsState.ps1
Labels: bug :ambulance:

#98 Updated Az target version, Subscription exclusion through QuotaID
  .azure-pipelines/ubuntu-latest.yml
  Dockerfile
  src/AzOps.psd1
  src/AzOps.psm1
  src/private/ConvertTo-AzOpsState.ps1
  src/private/Get-AzOpsAllSubscription.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
Labels: enhancement :rocket:, feature :bulb:

#100 Fix generalize templates variable
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
Labels: bug :ambulance:

#101 Fix ResourceGroupName and SubscriptionId exlusion in StateConfig
  src/AzOpsStateConfig.json
Labels: bug :ambulance:

#111 Updating Consistency Check Text
  src/Comments.md
  src/public/Invoke-AzOpsGitPush.ps1
Labels: enhancement :rocket:

#112 Add strict & automerge modes
  Dockerfile
  action.yml
  entrypoint.ps1
  src/auxiliary/guidance/default/README.md
  src/auxiliary/guidance/strict/README.md
  src/auxiliary/merge/README.md
  src/private/ConvertTo-AzOpsState.ps1
  src/private/Invoke-AzOpsGitPullRefresh.ps1
  src/private/Invoke-AzOpsGitPushRefresh.ps1
  src/private/Write-AzOpsLog.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  src/public/Invoke-AzOpsGitPull.ps1
  src/public/Invoke-AzOpsGitPush.ps1
Labels: feature :bulb:

#114 Enabling Opt-out for Auto merge
  src/public/Initialize-AzOpsGlobalVariables.ps1
Labels: enhancement :rocket:

#108 Enhancement - AzOpsState ordering
  src/AzOpsStateConfig.json
Labels: bug :ambulance:

#115 Adding -R option for gh pr merge to point to local fork
  src/public/Invoke-AzOpsGitPull.ps1
Labels: bug :ambulance:

#120 Enabling Clean up of IAB
  tests/AzOps.IAB.Tests.ps1
Labels: enhancement :rocket:

#122 Fix auto-merge delay
  src/public/Invoke-AzOpsGitPull.ps1
Labels: bug :ambulance:

#123 Adding paging support to retrieve subscription greater than 50 in a tenant
  src/private/Get-AzOpsAllSubscription.ps1
Labels: bug :ambulance:
