Repository Azure/AzOps, pull requests merged in 2020-06, with the labels that each got.

#7 Update *.parameters.json location
  template/10-create-managementgroup.parameters.json
  template/20-create-child-managementgroup.parameters.json
  template/30-create-policydefinition-at-managementgroup.parameters.json
  template/40-create-policyassignment-at-managementgroup.parameters.json
  template/60-move-subscription-under-managementgroup.parameters.json
  tests/AzOps.IAB.Tests.ps1
Labels: improvements

#10 Enable parallel jobs in pipeline
  .azure-pipelines/ubuntu-latest.yml
  tests/scripts/Initialize-AzOpsTestEnvironment.ps1
Labels: feature

#14 changing Write-Ouput to Write-AzOpsLog
  .gitignore
  src/Comments.md
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
Labels: improvement

#18 Logging review
  README.md
  entrypoint.ps1
  src/AzOps.psm1
  src/private/Compare-AzOpsState.ps1
  src/private/ConvertTo-AzOpsObject.ps1
  src/private/ConvertTo-AzOpsState.ps1
  src/private/ConvertTo-AzOpsTemplateParameterObject.ps1
  src/private/Get-AzOpsPolicyAssignmentAtScope.ps1
  src/private/Get-AzOpsPolicyDefinitionAtScope.ps1
  src/private/Get-AzOpsPolicySetDefinitionAtScope.ps1
  src/private/Get-AzOpsResourceDefinitionAtScope.ps1
  src/private/Get-AzOpsRoleAssignmentAtScope.ps1
  src/private/Get-AzOpsRoleDefinitionAtScope.ps1
  src/private/New-AzOpsStateDeployment.ps1
  src/private/Register-AzOpsProviderFeature.ps1
  src/private/Register-AzOpsResourceProvider.ps1
  src/private/Remove-AzOpsManagementGroup.ps1
  src/private/Save-AzOpsManagementGroupChildren.ps1
  src/private/Test-AzOpsDuplicateSubMgmtGroup.ps1
  src/private/Test-AzOpsVariables.ps1
  src/private/Write-AzOpsLog.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  src/public/Initialize-AzOpsRepository.ps1
  template/enterprise-scale-arm-template.json
  template/template.json
  template/tenant.json
  template/ux-foundation.json
  template/ux-hub-spoke.json
  template/ux-vwan.json
  tests/AzOps.Cmdlets.Tests.ps1
  tests/AzOps.IAB.Tests.ps1
  tests/AzOps.Scope.Tests.ps1
Labels: feature

#20 Add AzOpsLog dot source
  entrypoint.ps1
Labels: bug

#27 updating CI path to include template directory
  .azure-pipelines/ubuntu-latest.yml
Labels: improvement

#29 Update ubuntu-latest.yml
  .azure-pipelines/ubuntu-latest.yml
Labels: improvement

#26 adding enviornment variables
  action.yml
  entrypoint.ps1
Labels: feature

#24 updated managementGroup API version
  template/template.json
Labels: improvement

#23 updating API version for managementGroups
  template/tenant.json
Labels: improvement

#31 Versions
  Dockerfile
  action.yml
  src/AzOps.psd1
  tests/AzOps.Module.Tests.ps1
Labels: improvement

#35 Environment Variables
  src/private/Invoke-AzOpsGitPushRefresh.ps1
  src/public/Invoke-AzOpsGitPull.ps1
  src/public/Invoke-AzOpsGitPush.ps1
Labels: feature

#37 Fork Workflow Issue
  README.md
  src/public/Invoke-AzOpsGitPull.ps1
Labels: bug

#38 Bugfix for Discovery with "Tenant Root Goup" only is failing
  src/public/Initialize-AzOpsGlobalVariables.ps1
Labels: bug

#33 Link implementation guide to the article in CAF
  README.md
Labels: bug

#41 Badge Fix
  README.md
Labels: bug

#43 Ignoring markdown files
  .azure-pipelines/ubuntu-latest.yml
Labels: improvement

#44 Preference Logging
  Dockerfile
Labels: improvement

#45 Actions - Env Vars Improvements
  action.yml
  entrypoint.ps1
  src/Comments.md
  src/private/Invoke-AzOpsGitPullRefresh.ps1
  src/private/Invoke-AzOpsGitPushRefresh.ps1
  src/private/New-AzOpsStateDeployment.ps1
  src/public/Initialize-AzOpsGlobalVariables.ps1
  src/public/Invoke-AzOpsGitPull.ps1
  src/public/Invoke-AzOpsGitPush.ps1
Labels: feature

#46 Template update
  template/auxiliary/activityLog.json
  template/auxiliary/monitoring.json
  template/enterprise-scale-arm-template.json
  template/esux.json
  template/tenant.json
  template/ux-foundation.json
  template/ux-vwan.json
Labels: feature

#48 adding function to remove deployments
  src/private/Remove-AzOpsDeployments.ps1
Labels: feature

#56 Release version
  Dockerfile
  src/AzOps.psd1
  tests/AzOps.Module.Tests.ps1
Labels: process
