Repository Azure/AzOps, pull requests merged in 2021-07, with the labels that each got.

#398 Wiki updates
  docs/wiki/Debugging.md
  docs/wiki/Introduction.md
  docs/wiki/Prerequisites.md
  docs/wiki/Subscriptions.md
  docs/wiki/Updates.md
  docs/wiki/_Sidebar.md
Labels: bug

#403 Ordering of resourceGroup tags
  src/data/template/Microsoft.KeyVault/vaults.template.jq
  src/data/template/Microsoft.Resources/resourceGroups.template.jq
  src/internal/functions/Set-AzOpsWhatIfOutput.ps1
Labels: bug

#405 Add PR Template
  .github/PULL_REQUEST_TEMPALTE.md
Labels: enhancement

#406 Fix PR Template File Name
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#408 Adding support for policyExemptions
  docs/wiki/Introduction.md
  docs/wiki/Roadmap.md
  src/data/template/Microsoft.Authorization/policyExemptions.jq
  src/data/template/Microsoft.Authorization/policyExemptions.template.jq
  src/internal/functions/Get-AzOpsPolicyExemption.ps1
  src/internal/functions/Get-AzOpsResourceDefinition.ps1
  src/localized/en-us/Strings.psd1
Labels: area/powershell, enhancement

#409 Process files on git rename status with copy score
  src/functions/Invoke-AzOpsPush.ps1
Labels: enhancement
