Repository Azure/AzOps, pull requests merged in 2021-09, with the labels that each got.

#419 Added powershell version to Metadata of Template
  src/data/template/Microsoft.Authorization/policyAssignments.template.jq
  src/data/template/Microsoft.Authorization/policyDefinitions.template.jq
  src/data/template/Microsoft.Authorization/policyExemptions.template.jq
  src/data/template/Microsoft.Authorization/policySetDefinitions.template.jq
  src/data/template/Microsoft.Authorization/roleAssignments.template.jq
  src/data/template/Microsoft.Authorization/roleDefinitions.template.jq
  src/data/template/Microsoft.KeyVault/vaults.template.jq
  src/data/template/Microsoft.Management/managementGroups.template.jq
  src/data/template/Microsoft.Management/managementGroups/subscriptions.template.jq
  src/data/template/Microsoft.Resources/resourceGroups.template.jq
  src/data/template/template.jq
Labels: enhancement, area/powershell

#425 Fix to enumerate resourceProviders that are not registered in current context
  src/functions/Initialize-AzOpsEnvironment.ps1
Labels: bug, area/powershell

#428 Metadata for policyDefinitons/policySetdefinitions and update of dependencies
  src/AzOps.psd1
  src/data/template/Microsoft.Authorization/policyDefinitions.jq
  src/data/template/Microsoft.Authorization/policySetDefinitions.jq
Labels: enhancement
