Repository Azure/AzOps, pull requests merged in 2022-05, with the labels that each got.

#609 Adding additional controls for resource discovery
  docs/wiki/Frequently-Asked-Questions.md
  docs/wiki/Settings.md
  src/functions/Invoke-AzOpsPull.ps1
  src/internal/configurations/Core.ps1
  src/internal/functions/Get-AzOpsResourceDefinition.ps1
  src/localized/en-us/Strings.psd1
Labels: enhancement

#615 Wiki Setting Update
  docs/wiki/Settings.md
  src/tests/functional/README.md
Labels: wiki-doc

#618 Simplify/optimize Remove-AzOpsDeployment function
  src/internal/functions/Get-AzOpsContextPermissionCheck.ps1
  src/internal/functions/Remove-AzOpsDeployment.ps1
  src/localized/en-us/Strings.psd1
Labels: enhancement, area/powershell

#632 Cleanup of New-AzOpsDeployment and CustomSortOrder feature for Invoke-AzOpsPush
  src/functions/Invoke-AzOpsPush.ps1
  src/internal/functions/New-AzOpsDeployment.ps1
  src/tests/integration/Repository.Tests.ps1
  src/tests/templates/biceptest.bicep
  src/tests/templates/biceptest.parameters.json
Labels: enhancement, area/powershell

#635 Adding discovery support for Microsoft.Authorization/roleEligibilityScheduleRequests
  docs/wiki/Settings.md
  scripts/New-AzOpsTestsDeploymentHelper.ps1
  src/data/template/Microsoft.Authorization/roleEligibilityScheduleRequests.jq
  src/data/template/Microsoft.Authorization/roleEligibilityScheduleRequests.template.jq
  src/functions/Invoke-AzOpsPull.ps1
  src/internal/classes/AzOpsRoleEligibilityScheduleRequest.ps1
  src/internal/configurations/Core.ps1
  src/internal/functions/Get-AzOpsPim.ps1
  src/internal/functions/Get-AzOpsResourceDefinition.ps1
  src/internal/functions/Get-AzOpsRoleEligibilityScheduleRequest.ps1
  src/localized/en-us/Strings.psd1
  src/tests/Pester.ps1
  src/tests/functional/Functional.Tests.ps1
  src/tests/functional/Microsoft.Authorization/roleAssignments/deploy/deploy.bicep
  src/tests/functional/Microsoft.Authorization/roleEligibilityScheduleRequests/deploy/deploy.json
  src/tests/functional/Microsoft.Authorization/roleEligibilityScheduleRequests/deploy/deploy.parameters.json
  src/tests/functional/Microsoft.Authorization/roleEligibilityScheduleRequests/deploy/deploy.ps1
  src/tests/functional/Microsoft.Authorization/roleEligibilityScheduleRequests/scenario.ps1
  src/tests/functional/Microsoft.Network/azureFirewalls/deploy/deploy.parameters.json
  src/tests/integration/Repository.Tests.ps1
Labels: enhancement
