Repository Azure/AzOps, pull requests merged in 2022-04, with the labels that each got.

#584 Fix to VNet modules templates
  src/data/template/Microsoft.Network/virtualNetworks.jq
  src/functions/README.md
Labels: bug

#590 Added wiki article with guidance for running self-hosted agents/runners
  docs/wiki/Self-Hosted.md
  docs/wiki/_Sidebar.md
Labels: wiki-doc

#586 Update Template.jq with Kind and Sku parameters
  src/data/template/template.jq
Labels: enhancement
