Repository Azure/AzOps, pull requests merged in 2022-06, with the labels that each got.

#651 Improved error handling coming from failing resource providers
  src/internal/functions/Get-AzOpsResourceDefinition.ps1
  src/localized/en-us/Strings.psd1
Labels: enhancement

#655 Added type subscription when returning mgmtgrpname
  src/internal/classes/AzOpsScope.ps1
Labels: bug

#659 Fix verbose log message
  src/functions/Invoke-AzOpsPush.ps1
  src/localized/en-us/Strings.psd1
Labels: bug

#663 Adding Automated testing for Core.PartialMgDiscoveryRoot
  .gitignore
  src/tests/functional/Functional.Tests.ps1
  src/tests/integration/Repository.Tests.ps1
  src/tests/templates/azuredeploy.jsonc
Labels: tests
