Repository Azure/AzOps, pull requests merged in 2022-12, with the labels that each got.

#718 Expand support for management group deployment
  src/internal/classes/AzOpsScope.ps1
  src/internal/functions/New-AzOpsDeployment.ps1
  src/localized/en-us/Strings.psd1
  src/tests/integration/Repository.Tests.ps1
  src/tests/templates/pushmgmttest1displayname (pushmgmttest1id)/microsoft.management_managementgroups-pushmgmttest1id.json
  src/tests/templates/pushmgmttest2displayname (pushmgmttest2id)/microsoft.management_managementgroups-pushmgmttest2id.json
Labels: enhancement

#719 Fix headlines for WhatIf output
  src/internal/functions/New-AzOpsDeployment.ps1
  src/internal/functions/Remove-AzOpsDeployment.ps1
  src/internal/functions/Set-AzOpsWhatIfOutput.ps1
Labels: enhancement

#723 Remove `Directory Readers` Azure AD role requirement for `roleAssignments` pull
  docs/wiki/Prerequisites.md
  src/functions/Invoke-AzOpsPull.ps1
  src/localized/en-us/Strings.psd1
Labels: area/powershell

#724 Update Management Group DisplayName
  src/internal/classes/AzOpsScope.ps1
  src/localized/en-us/Strings.psd1
Labels: bug

#733 Bicep deployment fix for parameter file updates
  src/functions/Invoke-AzOpsPush.ps1
  src/internal/classes/AzOpsScope.ps1
  src/internal/functions/ConvertFrom-AzOpsBicepTemplate.ps1
  src/localized/en-us/Strings.psd1
Labels: bug, enhancement
