Repository Azure/AzOps, pull requests merged in 2023-03, with the labels that each got.

#766 Update Wiki OIDC
  docs/wiki/GitHub-OIDC.md
  docs/wiki/Media/oidc/add.png
  docs/wiki/Media/oidc/addcreds.png
  docs/wiki/Media/oidc/connect_github_account.png
  docs/wiki/Media/oidc/credential_details.png
  docs/wiki/Media/oidc/spn_addcreds2.jpg
  docs/wiki/Media/oidc/spn_addcreds2.png
  docs/wiki/Media/oidc/spn_added.jpg
  docs/wiki/Media/oidc/uami.png
Labels: wiki-doc

#768 Throw exception on failing bicep build
  src/internal/functions/ConvertFrom-AzOpsBicepTemplate.ps1
  src/localized/en-us/Strings.psd1
  src/tests/integration/Repository.Tests.ps1
  src/tests/templates/biceperror.bicep
Labels: enhancement

#769 Bump Dependencies
  src/AzOps.psd1
Labels: dependencies

#770 fixing broken link
  docs/wiki/Azure-Pipelines.md
Labels: wiki-doc

#764 Adding Removal of Lingering Files
  docs/wiki/Frequently-Asked-Questions.md
  docs/wiki/Self-Hosted.md
  src/functions/Initialize-AzOpsEnvironment.ps1
  src/functions/Invoke-AzOpsPush.ps1
  src/localized/en-us/Strings.psd1
Labels: wiki-doc, enhancement, do not merge

#773 Fix regression of #538
  src/data/template/Microsoft.Authorization/policyAssignments.jq
  src/tests/integration/Repository.Tests.ps1
  src/tests/templates/policywithuam.bicep
Labels: bug

#778 Fix regression of Subscription Only Discovery with no Management Group
  .github/workflows/tests.yml
  scripts/Remove-AzOpsTestsDeployment.ps1
  src/data/template/Microsoft.Subscription/subscriptions.template.jq
  src/functions/Invoke-AzOpsPull.ps1
  src/internal/functions/ConvertTo-AzOpsState.ps1
  src/tests/Pester.ps1
  src/tests/integration/Repository.Tests.ps1
  src/tests/subscriptiononly/SubOnly.Tests.ps1
  src/tests/templates/rgsubonlydeploy.bicep
  src/tests/templates/rgsubonlydeploy.parameters.json
  src/tests/templates/stasubonlydeploy.bicep
Labels: bug

#771 Removal of legacy migration wiki
  docs/wiki/Migration.md
  docs/wiki/_Sidebar.md
Labels: wiki-doc, waiting-for-response

#779 Release 2.1.1
  src/AzOps.psd1
Labels: release

#782 Release 2.1.2
  src/AzOps.psd1
Labels: release
