Repository Azure/AzOps, pull requests merged in 2023-02, with the labels that each got.

#746 Updated documentation for GitHub/Azure AD federated credentials
  docs/wiki/GitHub-Actions.md
  docs/wiki/GitHub-OIDC.md
  docs/wiki/Prerequisites.md
Labels: enhancement, area/accelerator

#751 Patch apiVersion on nested microsoft.authorization/policydefinitions resources
  src/internal/functions/Get-AzOpsPolicy.ps1
Labels: bug

#759 Update Docs
  docs/wiki/Settings.md
Labels: wiki-doc

#760 Adding Wiki Performance-Considerations
  docs/wiki/Media/AdjustingThrottleLimit.png
  docs/wiki/Performance-Considerations.md
  docs/wiki/Settings.md
  docs/wiki/_Sidebar.md
Labels: wiki-doc

#761 Reliability improvements
  scripts/Remove-AzOpsTestsDeployment.ps1
  src/functions/Initialize-AzOpsEnvironment.ps1
  src/internal/configurations/Core.ps1
  src/internal/functions/ConvertTo-AzOpsState.ps1
  src/internal/functions/Get-AzOpsPolicyExemption.ps1
  src/internal/functions/Get-AzOpsResourceDefinition.ps1
  src/internal/functions/Get-AzOpsResourceLock.ps1
  src/internal/functions/Get-AzOpsRoleAssignment.ps1
  src/internal/functions/Get-AzOpsRoleDefinition.ps1
  src/internal/functions/Invoke-AzOpsRestMethod.ps1
  src/internal/functions/Remove-AzOpsInvalidCharacter.ps1
  src/localized/en-us/Strings.psd1
Labels: enhancement, area/powershell
