Repository Azure/AzOps, pull requests merged in 2024-04, with the labels that each got.

#871 Update - Microsoft.Management missing from Subscription during Initialize
  docs/wiki/Frequently-Asked-Questions.md
  docs/wiki/Prerequisites.md
  src/functions/Initialize-AzOpsEnvironment.ps1
  src/localized/en-us/Strings.psd1
Labels: wiki-doc, enhancement

#872 Update Template Api Versions
  scripts/New-AzOpsTestsDeploymentHelper.ps1
  src/AzOps.psd1
  src/data/template/template.json
  src/internal/functions/New-AzOpsDeployment.ps1
  src/tests/integration/Repository.Tests.ps1
  src/tests/subscriptiononly/SubOnly.Tests.ps1
Labels: bug, enhancement, dependencies

#873 Release 2.6.1
  src/AzOps.psd1
Labels: release

#875 Fix Jq filter to allow empty defaultValue for policy definition and set definition
  src/data/template/Microsoft.Authorization/policyDefinitions.jq
  src/data/template/Microsoft.Authorization/policySetDefinitions.jq
Labels: bug

#877 Release 2.6.2
  src/AzOps.psd1
Labels: release
