Repository Azure/AzOps, pull requests merged in 2024-12, with the labels that each got.

#902 Added additional constructor for AzOpsRoleEligibilityScheduleRequest
  src/AzOps.psd1
  src/internal/classes/AzOpsRoleEligibilityScheduleRequest.ps1
  src/internal/functions/Get-AzOpsRoleEligibilityScheduleRequest.ps1
  src/localized/en-us/Strings.psd1
  src/tests/templates/azuredeploy.jsonc
Labels: bug, dependencies

#900 Added retry capability for pulling PIM resources
  src/internal/functions/Get-AzOpsRoleEligibilityScheduleRequest.ps1
  src/localized/en-us/Strings.psd1
Labels: enhancement, area/powershell

#907 Release 2.6.6
  src/AzOps.psd1
Labels: release

#908 Fix Resource Existence Validation Error Logic
  src/internal/functions/Get-AzOpsResource.ps1
  src/localized/en-us/Strings.psd1
Labels: bug

#909 v2.6.7
  src/AzOps.psd1
Labels: release
